//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CosmosConsoleClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CosmosConsoleClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ID of the container to create, if it does not already exist..
        /// </summary>
        internal static string ArgDescContainerCreateId {
            get {
                return ResourceManager.GetString("ArgDescContainerCreateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the database to operate on..
        /// </summary>
        internal static string ArgDescContainerDatabaseId {
            get {
                return ResourceManager.GetString("ArgDescContainerDatabaseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete an existing container.
        ///NOTE: An exception will be thrown if either the DB or container does not exist..
        /// </summary>
        internal static string ArgDescContainerDeleteId {
            get {
                return ResourceManager.GetString("ArgDescContainerDeleteId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializes/creates the specified database if it does not exist..
        /// </summary>
        internal static string ArgDescContainerInitDB {
            get {
                return ResourceManager.GetString("ArgDescContainerInitDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partition key path..
        /// </summary>
        internal static string ArgDescContainerPartitionPath {
            get {
                return ResourceManager.GetString("ArgDescContainerPartitionPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throughput (RU/sec)..
        /// </summary>
        internal static string ArgDescContainerThroughput {
            get {
                return ResourceManager.GetString("ArgDescContainerThroughput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ID of the database to create, if it does not already exist..
        /// </summary>
        internal static string ArgDescDatabaseCreateId {
            get {
                return ResourceManager.GetString("ArgDescDatabaseCreateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete an existing database.
        ///NOTE: An exception will be thrown if the DB does not exist..
        /// </summary>
        internal static string ArgDescDatabaseDeleteId {
            get {
                return ResourceManager.GetString("ArgDescDatabaseDeleteId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the container to operate on..
        /// </summary>
        internal static string ArgDescItemContainerId {
            get {
                return ResourceManager.GetString("ArgDescItemContainerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The JSON data to write to a new item in the specified container.
        ///NOTE: An exception will be thrown if the container does not exist..
        /// </summary>
        internal static string ArgDescItemCreateItem {
            get {
                return ResourceManager.GetString("ArgDescItemCreateItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the database to operate on..
        /// </summary>
        internal static string ArgDescItemDatabaseId {
            get {
                return ResourceManager.GetString("ArgDescItemDatabaseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item, containing the specified ID (example: GUID), to delete.
        ///NOTE: An exception will be thrown if the container does not exist..
        /// </summary>
        internal static string ArgDescItemDeleteId {
            get {
                return ResourceManager.GetString("ArgDescItemDeleteId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializes/creates the specified database and/or container if they do not exist..
        /// </summary>
        internal static string ArgDescItemInitAll {
            get {
                return ResourceManager.GetString("ArgDescItemInitAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partition key value.
        ///NOTE: If omitted, the ID and partition key value will be assumed to be the same..
        /// </summary>
        internal static string ArgDescItemPartitionKey {
            get {
                return ResourceManager.GetString("ArgDescItemPartitionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partition key path.
        ///NOTE: If omitted, the ID will be inferred..
        /// </summary>
        internal static string ArgDescItemPartitionPath {
            get {
                return ResourceManager.GetString("ArgDescItemPartitionPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throughput (RU/sec).
        /// </summary>
        internal static string ArgDescItemThroughput {
            get {
                return ResourceManager.GetString("ArgDescItemThroughput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interact with Cosmos DB container management.
        /// </summary>
        internal static string CmdDescContainer {
            get {
                return ResourceManager.GetString("CmdDescContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interact with Cosmos DB database management.
        /// </summary>
        internal static string CmdDescDatabase {
            get {
                return ResourceManager.GetString("CmdDescDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interact with Cosmos DB item management.
        /// </summary>
        internal static string CmdDescItem {
            get {
                return ResourceManager.GetString("CmdDescItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A command line utility for interacting with an instance of Cosmos DB..
        /// </summary>
        internal static string CmdDescRoot {
            get {
                return ResourceManager.GetString("CmdDescRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. ({0}).
        /// </summary>
        internal static string LogMsgError {
            get {
                return ResourceManager.GetString("LogMsgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Charge: {0}.
        /// </summary>
        internal static string LogMsgRequestCharge {
            get {
                return ResourceManager.GetString("LogMsgRequestCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success. ({0}).
        /// </summary>
        internal static string LogMsgSuccess {
            get {
                return ResourceManager.GetString("LogMsgSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One and only one of the following options shall be present: {0}, {1}.
        /// </summary>
        internal static string ValidateErrMsgCreateXorDelete {
            get {
                return ResourceManager.GetString("ValidateErrMsgCreateXorDelete", resourceCulture);
            }
        }
    }
}
